// Copyright (c) 2024 Princeton University
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the copyright holder nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Automatically generated by PRGA's RTL generator
`include "pktchain.vh"
`timescale 1ns/1ps
module pktchain_frame_disassemble #(
    parameter DEPTH_LOG2 = 1,   // depth in terms of frames
    parameter DATA_WIDTH_LOG2 = `PRGA_PKTCHAIN_FRAME_SIZE_LOG2
) (
    input wire [0:0] prog_clk,
    input wire [0:0] prog_rst,

    output wire [0:0] frame_full,
    input wire [0:0] frame_wr,
    input wire [(1 << DATA_WIDTH_LOG2) - 1:0] frame_i,

    output wire [0:0] phit_wr,
    input wire [0:0] phit_full,
    output wire [`PRGA_PKTCHAIN_PHIT_WIDTH - 1:0] phit_o
    );

    wire resizer_rd, resizer_empty, fifo_full, fifo_empty, fifo_rd;
    wire [`PRGA_PKTCHAIN_PHIT_WIDTH - 1:0] resizer_dout, fifo_dout;

    assign frame_full = ~resizer_rd;

    prga_fifo_resizer #(
        .DATA_WIDTH                 (`PRGA_PKTCHAIN_PHIT_WIDTH)
        ,.INPUT_MULTIPLIER          (1 << (DATA_WIDTH_LOG2 - `PRGA_PKTCHAIN_PHIT_WIDTH_LOG2))
        ,.INPUT_LOOKAHEAD           (1)
        ,.OUTPUT_LOOKAHEAD          (1)
    ) resizer (
        .clk                        (prog_clk)
        ,.rst                       (prog_rst)
        ,.empty_i                   (~frame_wr)
        ,.rd_i                      (resizer_rd)
        ,.dout_i                    (frame_i)
        ,.empty                     (resizer_empty)
        ,.rd                        (~fifo_full)
        ,.dout                      (resizer_dout)
        );

    prga_fifo #(
        .DATA_WIDTH                 (`PRGA_PKTCHAIN_PHIT_WIDTH)
        ,.LOOKAHEAD                 (0)
        ,.DEPTH_LOG2                (DEPTH_LOG2)
    ) fifo (
        .clk                        (prog_clk)
        ,.rst                       (prog_rst)
        ,.full                      (fifo_full)
        ,.wr                        (~resizer_empty)
        ,.din                       (resizer_dout)
        ,.empty                     (fifo_empty)
        ,.rd                        (fifo_rd)
        ,.dout                      (fifo_dout)
        );

    prga_fifo_adapter #(
        .DATA_WIDTH                 (`PRGA_PKTCHAIN_PHIT_WIDTH)
        ,.INPUT_LOOKAHEAD           (0)
    ) adapter (
        .clk                        (prog_clk)
        ,.rst                       (prog_rst)
        ,.empty_i                   (fifo_empty)
        ,.rd_i                      (fifo_rd)
        ,.dout_i                    (fifo_dout)
        ,.wr_o                      (phit_wr)
        ,.full_o                    (phit_full)
        ,.din_o                     (phit_o)                  
        );

endmodule