// Copyright (c) 2024 Princeton University
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the copyright holder nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module prga_clb (
    input wire [0:0] clk
    , input wire [0:0] ce
    , input wire [31:0] in
    , output wire [15:0] out
    , input wire [0:0] cin
    , output wire [0:0] cout
    , input wire [0:0] prog_clk
    , input wire [0:0] prog_rst
    , input wire [0:0] prog_done
    , input wire [0:0] prog_we
    , input wire [0:0] prog_din
    , output wire [0:0] prog_dout
    , output wire [0:0] prog_we_o
    );
    
        
    wire [1:0] _i_slice_i0__out;
    wire [0:0] _i_slice_i0__cout;
    wire [1:0] _i_slice_i1__out;
    wire [0:0] _i_slice_i1__cout;
    wire [1:0] _i_slice_i2__out;
    wire [0:0] _i_slice_i2__cout;
    wire [1:0] _i_slice_i3__out;
    wire [0:0] _i_slice_i3__cout;
    wire [1:0] _i_slice_i4__out;
    wire [0:0] _i_slice_i4__cout;
    wire [1:0] _i_slice_i5__out;
    wire [0:0] _i_slice_i5__cout;
    wire [1:0] _i_slice_i6__out;
    wire [0:0] _i_slice_i6__cout;
    wire [1:0] _i_slice_i7__out;
    wire [0:0] _i_slice_i7__cout;
    wire [0:0] _i_sw_i_slice_i0_in_0__o;
    wire [0:0] _i_sw_i_slice_i0_in_1__o;
    wire [0:0] _i_sw_i_slice_i0_in_2__o;
    wire [0:0] _i_sw_i_slice_i0_in_3__o;
    wire [0:0] _i_sw_i_slice_i0_in_4__o;
    wire [0:0] _i_sw_i_slice_i0_in_5__o;
    wire [0:0] _i_sw_i_slice_i0_in_6__o;
    wire [0:0] _i_sw_i_slice_i0_in_7__o;
    wire [0:0] _i_sw_i_slice_i1_in_0__o;
    wire [0:0] _i_sw_i_slice_i1_in_1__o;
    wire [0:0] _i_sw_i_slice_i1_in_2__o;
    wire [0:0] _i_sw_i_slice_i1_in_3__o;
    wire [0:0] _i_sw_i_slice_i1_in_4__o;
    wire [0:0] _i_sw_i_slice_i1_in_5__o;
    wire [0:0] _i_sw_i_slice_i1_in_6__o;
    wire [0:0] _i_sw_i_slice_i1_in_7__o;
    wire [0:0] _i_sw_i_slice_i2_in_0__o;
    wire [0:0] _i_sw_i_slice_i2_in_1__o;
    wire [0:0] _i_sw_i_slice_i2_in_2__o;
    wire [0:0] _i_sw_i_slice_i2_in_3__o;
    wire [0:0] _i_sw_i_slice_i2_in_4__o;
    wire [0:0] _i_sw_i_slice_i2_in_5__o;
    wire [0:0] _i_sw_i_slice_i2_in_6__o;
    wire [0:0] _i_sw_i_slice_i2_in_7__o;
    wire [0:0] _i_sw_i_slice_i3_in_0__o;
    wire [0:0] _i_sw_i_slice_i3_in_1__o;
    wire [0:0] _i_sw_i_slice_i3_in_2__o;
    wire [0:0] _i_sw_i_slice_i3_in_3__o;
    wire [0:0] _i_sw_i_slice_i3_in_4__o;
    wire [0:0] _i_sw_i_slice_i3_in_5__o;
    wire [0:0] _i_sw_i_slice_i3_in_6__o;
    wire [0:0] _i_sw_i_slice_i3_in_7__o;
    wire [0:0] _i_sw_i_slice_i4_in_0__o;
    wire [0:0] _i_sw_i_slice_i4_in_1__o;
    wire [0:0] _i_sw_i_slice_i4_in_2__o;
    wire [0:0] _i_sw_i_slice_i4_in_3__o;
    wire [0:0] _i_sw_i_slice_i4_in_4__o;
    wire [0:0] _i_sw_i_slice_i4_in_5__o;
    wire [0:0] _i_sw_i_slice_i4_in_6__o;
    wire [0:0] _i_sw_i_slice_i4_in_7__o;
    wire [0:0] _i_sw_i_slice_i5_in_0__o;
    wire [0:0] _i_sw_i_slice_i5_in_1__o;
    wire [0:0] _i_sw_i_slice_i5_in_2__o;
    wire [0:0] _i_sw_i_slice_i5_in_3__o;
    wire [0:0] _i_sw_i_slice_i5_in_4__o;
    wire [0:0] _i_sw_i_slice_i5_in_5__o;
    wire [0:0] _i_sw_i_slice_i5_in_6__o;
    wire [0:0] _i_sw_i_slice_i5_in_7__o;
    wire [0:0] _i_sw_i_slice_i6_in_0__o;
    wire [0:0] _i_sw_i_slice_i6_in_1__o;
    wire [0:0] _i_sw_i_slice_i6_in_2__o;
    wire [0:0] _i_sw_i_slice_i6_in_3__o;
    wire [0:0] _i_sw_i_slice_i6_in_4__o;
    wire [0:0] _i_sw_i_slice_i6_in_5__o;
    wire [0:0] _i_sw_i_slice_i6_in_6__o;
    wire [0:0] _i_sw_i_slice_i6_in_7__o;
    wire [0:0] _i_sw_i_slice_i7_in_0__o;
    wire [0:0] _i_sw_i_slice_i7_in_1__o;
    wire [0:0] _i_sw_i_slice_i7_in_2__o;
    wire [0:0] _i_sw_i_slice_i7_in_3__o;
    wire [0:0] _i_sw_i_slice_i7_in_4__o;
    wire [0:0] _i_sw_i_slice_i7_in_5__o;
    wire [0:0] _i_sw_i_slice_i7_in_6__o;
    wire [0:0] _i_sw_i_slice_i7_in_7__o;
    wire [0:0] _i_buf_prog_rst_l0__Q;
    wire [0:0] _i_buf_prog_done_l0__Q;
    wire [0:0] _i_scanchain_head__prog_dout;
    wire [0:0] _i_scanchain_head__prog_we_o;
    wire [0:0] _i_prog_data_i_slice_i0__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i0__prog_data;
    wire [0:0] _i_prog_data_i_slice_i1__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i1__prog_data;
    wire [0:0] _i_prog_data_i_slice_i2__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i2__prog_data;
    wire [0:0] _i_prog_data_i_slice_i3__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i3__prog_data;
    wire [0:0] _i_prog_data_i_slice_i4__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i4__prog_data;
    wire [0:0] _i_prog_data_i_slice_i5__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i5__prog_data;
    wire [0:0] _i_prog_data_i_slice_i6__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i6__prog_data;
    wire [0:0] _i_prog_data_i_slice_i7__prog_dout;
    wire [75:0] _i_prog_data_i_slice_i7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i0_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i0_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i1_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i1_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i2_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i2_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i3_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i3_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i4_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i4_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i5_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i5_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i6_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i6_in_7__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_0__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_0__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_1__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_1__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_2__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_2__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_3__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_3__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_4__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_4__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_5__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_5__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_6__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_6__prog_data;
    wire [0:0] _i_prog_data_i_sw_i_slice_i7_in_7__prog_dout;
    wire [4:0] _i_prog_data_i_sw_i_slice_i7_in_7__prog_data;
    wire [0:0] _i_scanchain_tail__prog_dout;
    wire [0:0] _i_scanchain_tail__prog_we_o;
        
    grady18v2 i_slice_i0 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i0_in_7__o,
            _i_sw_i_slice_i0_in_6__o,
            _i_sw_i_slice_i0_in_5__o,
            _i_sw_i_slice_i0_in_4__o,
            _i_sw_i_slice_i0_in_3__o,
            _i_sw_i_slice_i0_in_2__o,
            _i_sw_i_slice_i0_in_1__o,
            _i_sw_i_slice_i0_in_0__o})
        ,.ce(ce)
        ,.cin(cin)
        ,.out(_i_slice_i0__out)
        ,.cout(_i_slice_i0__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i0__prog_data)
        );
    grady18v2 i_slice_i1 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i1_in_7__o,
            _i_sw_i_slice_i1_in_6__o,
            _i_sw_i_slice_i1_in_5__o,
            _i_sw_i_slice_i1_in_4__o,
            _i_sw_i_slice_i1_in_3__o,
            _i_sw_i_slice_i1_in_2__o,
            _i_sw_i_slice_i1_in_1__o,
            _i_sw_i_slice_i1_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i0__cout)
        ,.out(_i_slice_i1__out)
        ,.cout(_i_slice_i1__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i1__prog_data)
        );
    grady18v2 i_slice_i2 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i2_in_7__o,
            _i_sw_i_slice_i2_in_6__o,
            _i_sw_i_slice_i2_in_5__o,
            _i_sw_i_slice_i2_in_4__o,
            _i_sw_i_slice_i2_in_3__o,
            _i_sw_i_slice_i2_in_2__o,
            _i_sw_i_slice_i2_in_1__o,
            _i_sw_i_slice_i2_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i1__cout)
        ,.out(_i_slice_i2__out)
        ,.cout(_i_slice_i2__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i2__prog_data)
        );
    grady18v2 i_slice_i3 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i3_in_7__o,
            _i_sw_i_slice_i3_in_6__o,
            _i_sw_i_slice_i3_in_5__o,
            _i_sw_i_slice_i3_in_4__o,
            _i_sw_i_slice_i3_in_3__o,
            _i_sw_i_slice_i3_in_2__o,
            _i_sw_i_slice_i3_in_1__o,
            _i_sw_i_slice_i3_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i2__cout)
        ,.out(_i_slice_i3__out)
        ,.cout(_i_slice_i3__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i3__prog_data)
        );
    grady18v2 i_slice_i4 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i4_in_7__o,
            _i_sw_i_slice_i4_in_6__o,
            _i_sw_i_slice_i4_in_5__o,
            _i_sw_i_slice_i4_in_4__o,
            _i_sw_i_slice_i4_in_3__o,
            _i_sw_i_slice_i4_in_2__o,
            _i_sw_i_slice_i4_in_1__o,
            _i_sw_i_slice_i4_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i3__cout)
        ,.out(_i_slice_i4__out)
        ,.cout(_i_slice_i4__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i4__prog_data)
        );
    grady18v2 i_slice_i5 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i5_in_7__o,
            _i_sw_i_slice_i5_in_6__o,
            _i_sw_i_slice_i5_in_5__o,
            _i_sw_i_slice_i5_in_4__o,
            _i_sw_i_slice_i5_in_3__o,
            _i_sw_i_slice_i5_in_2__o,
            _i_sw_i_slice_i5_in_1__o,
            _i_sw_i_slice_i5_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i4__cout)
        ,.out(_i_slice_i5__out)
        ,.cout(_i_slice_i5__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i5__prog_data)
        );
    grady18v2 i_slice_i6 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i6_in_7__o,
            _i_sw_i_slice_i6_in_6__o,
            _i_sw_i_slice_i6_in_5__o,
            _i_sw_i_slice_i6_in_4__o,
            _i_sw_i_slice_i6_in_3__o,
            _i_sw_i_slice_i6_in_2__o,
            _i_sw_i_slice_i6_in_1__o,
            _i_sw_i_slice_i6_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i5__cout)
        ,.out(_i_slice_i6__out)
        ,.cout(_i_slice_i6__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i6__prog_data)
        );
    grady18v2 i_slice_i7 (
        .clk(clk)
        ,.in({_i_sw_i_slice_i7_in_7__o,
            _i_sw_i_slice_i7_in_6__o,
            _i_sw_i_slice_i7_in_5__o,
            _i_sw_i_slice_i7_in_4__o,
            _i_sw_i_slice_i7_in_3__o,
            _i_sw_i_slice_i7_in_2__o,
            _i_sw_i_slice_i7_in_1__o,
            _i_sw_i_slice_i7_in_0__o})
        ,.ce(ce)
        ,.cin(_i_slice_i6__cout)
        ,.out(_i_slice_i7__out)
        ,.cout(_i_slice_i7__cout)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_slice_i7__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i0_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i0_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i0_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i0_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i0_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i0_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i0_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i0_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i0_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i1_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i1_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i1_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i1_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i1_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i1_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i1_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i1_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i1_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i2_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i2_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i2_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i2_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i2_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i2_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i2_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i2_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i2_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i3_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i3_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i3_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i3_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i3_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i3_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i3_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i3_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i3_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i4_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i4_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i4_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i4_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i4_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i4_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i4_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i4_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i4_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i5_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i5_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i5_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i5_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i5_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i5_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i5_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i5_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i5_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i6_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i6_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i6_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i6_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i6_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i6_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i6_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i6_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i6_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_7__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_0 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i7_in_0__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_0__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_1 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i7_in_1__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_1__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_2 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i7_in_2__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_2__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_3 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i7_in_3__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_3__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_4 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i7_in_4__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_4__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_5 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i7_in_5__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_5__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_6 (
        .i({_i_slice_i7__out[0],
            _i_slice_i6__out[0],
            _i_slice_i5__out[0],
            _i_slice_i4__out[0],
            _i_slice_i3__out[0],
            _i_slice_i2__out[0],
            _i_slice_i1__out[0],
            _i_slice_i0__out[0],
            in[30],
            in[28],
            in[26],
            in[24],
            in[22],
            in[20],
            in[18],
            in[16],
            in[14],
            in[12],
            in[10],
            in[8],
            in[6],
            in[4],
            in[2],
            in[0]})
        ,.o(_i_sw_i_slice_i7_in_6__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_6__prog_data)
        );
    sw24 i_sw_i_slice_i7_in_7 (
        .i({_i_slice_i7__out[1],
            _i_slice_i6__out[1],
            _i_slice_i5__out[1],
            _i_slice_i4__out[1],
            _i_slice_i3__out[1],
            _i_slice_i2__out[1],
            _i_slice_i1__out[1],
            _i_slice_i0__out[1],
            in[31],
            in[29],
            in[27],
            in[25],
            in[23],
            in[21],
            in[19],
            in[17],
            in[15],
            in[13],
            in[11],
            in[9],
            in[7],
            in[5],
            in[3],
            in[1]})
        ,.o(_i_sw_i_slice_i7_in_7__o)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_7__prog_data)
        );
    prga_simple_buf i_buf_prog_rst_l0 (
        .C(prog_clk)
        ,.D(prog_rst)
        ,.Q(_i_buf_prog_rst_l0__Q)
        );
    prga_simple_bufr i_buf_prog_done_l0 (
        .C(prog_clk)
        ,.R(_i_buf_prog_rst_l0__Q)
        ,.D(prog_done)
        ,.Q(_i_buf_prog_done_l0__Q)
        );
    scanchain_delim i_scanchain_head (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(prog_we)
        ,.prog_din(prog_din)
        ,.prog_dout(_i_scanchain_head__prog_dout)
        ,.prog_we_o(_i_scanchain_head__prog_we_o)
        );
    scanchain_data_d76 i_prog_data_i_slice_i0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_scanchain_head__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i0__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i0__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i0__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i1__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i1__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i1__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i2__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i2__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i2__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i3__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i3__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i3__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i4__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i4__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i4__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i5__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i5__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i5__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i6__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i6__prog_data)
        );
    scanchain_data_d76 i_prog_data_i_slice_i7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i6__prog_dout)
        ,.prog_dout(_i_prog_data_i_slice_i7__prog_dout)
        ,.prog_data(_i_prog_data_i_slice_i7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_slice_i7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i0_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i0_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i0_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i0_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i1_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i1_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i1_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i1_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i2_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i2_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i2_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i2_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i3_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i3_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i3_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i3_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i4_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i4_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i4_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i4_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i5_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i5_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i5_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i5_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i6_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i6_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i6_in_7__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_0 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i6_in_7__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_0__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_0__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_1 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_0__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_1__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_1__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_2 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_1__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_2__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_2__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_3 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_2__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_3__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_3__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_4 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_3__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_4__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_4__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_5 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_4__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_5__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_5__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_6 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_5__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_6__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_6__prog_data)
        );
    scanchain_data_d5 i_prog_data_i_sw_i_slice_i7_in_7 (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_6__prog_dout)
        ,.prog_dout(_i_prog_data_i_sw_i_slice_i7_in_7__prog_dout)
        ,.prog_data(_i_prog_data_i_sw_i_slice_i7_in_7__prog_data)
        );
    scanchain_delim i_scanchain_tail (
        .prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l0__Q)
        ,.prog_done(_i_buf_prog_done_l0__Q)
        ,.prog_we(_i_scanchain_head__prog_we_o)
        ,.prog_din(_i_prog_data_i_sw_i_slice_i7_in_7__prog_dout)
        ,.prog_dout(_i_scanchain_tail__prog_dout)
        ,.prog_we_o(_i_scanchain_tail__prog_we_o)
        );
        
    assign out = {_i_slice_i7__out,
        _i_slice_i6__out,
        _i_slice_i5__out,
        _i_slice_i4__out,
        _i_slice_i3__out,
        _i_slice_i2__out,
        _i_slice_i1__out,
        _i_slice_i0__out};
    assign cout = _i_slice_i7__cout;
    assign prog_dout = _i_scanchain_tail__prog_dout;
    assign prog_we_o = _i_scanchain_tail__prog_we_o;

endmodule
