// Copyright (c) 2024 Princeton University
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the copyright holder nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module prga_t_iob (
    input wire [19:0] bi_u1y0n_L1
    , input wire [19:0] bi_u1y0s_L1
    , output wire [19:0] cu_u1y0n_L1
    , output wire [19:0] cu_u1y0s_L1
    , input wire [19:0] bi_u1y0n_L4
    , input wire [19:0] bi_u1y0s_L4
    , input wire [19:0] bi_u1v2n_L4
    , input wire [19:0] bi_u1y2s_L4
    , output wire [19:0] cu_u1y0n_L4
    , output wire [19:0] cu_u1y0s_L4
    , input wire [19:0] bi_u1v1n_L4
    , input wire [19:0] bi_u1y1s_L4
    , input wire [19:0] bi_u1v3n_L4
    , input wire [19:0] bi_u1y3s_L4
    , input wire [0:0] ipin_x0y0_0
    , output wire [0:0] opin_x0y0_0
    , output wire [0:0] oe_x0y0_0
    , input wire [0:0] ipin_x0y0_1
    , output wire [0:0] opin_x0y0_1
    , output wire [0:0] oe_x0y0_1
    , input wire [0:0] ipin_x0y0_2
    , output wire [0:0] opin_x0y0_2
    , output wire [0:0] oe_x0y0_2
    , input wire [0:0] ipin_x0y0_3
    , output wire [0:0] opin_x0y0_3
    , output wire [0:0] oe_x0y0_3
    , input wire [0:0] ipin_x0y0_4
    , output wire [0:0] opin_x0y0_4
    , output wire [0:0] oe_x0y0_4
    , input wire [0:0] ipin_x0y0_5
    , output wire [0:0] opin_x0y0_5
    , output wire [0:0] oe_x0y0_5
    , input wire [0:0] ipin_x0y0_6
    , output wire [0:0] opin_x0y0_6
    , output wire [0:0] oe_x0y0_6
    , input wire [0:0] ipin_x0y0_7
    , output wire [0:0] opin_x0y0_7
    , output wire [0:0] oe_x0y0_7
    , input wire [0:0] ipin_x0y0_8
    , output wire [0:0] opin_x0y0_8
    , output wire [0:0] oe_x0y0_8
    , input wire [0:0] ipin_x0y0_9
    , output wire [0:0] opin_x0y0_9
    , output wire [0:0] oe_x0y0_9
    , input wire [0:0] prog_clk
    , input wire [0:0] prog_rst
    , input wire [0:0] prog_done
    , input wire [0:0] prog_we
    , input wire [0:0] prog_din
    , output wire [0:0] prog_dout
    , output wire [0:0] prog_we_o
    );
    
        
    wire [0:0] _i_blk_i0__inpad;
    wire [0:0] _i_blk_i0__opin;
    wire [0:0] _i_blk_i0__oe;
    wire [0:0] _i_blk_i0__prog_dout;
    wire [0:0] _i_blk_i0__prog_we_o;
    wire [0:0] _i_blk_i1__inpad;
    wire [0:0] _i_blk_i1__opin;
    wire [0:0] _i_blk_i1__oe;
    wire [0:0] _i_blk_i1__prog_dout;
    wire [0:0] _i_blk_i1__prog_we_o;
    wire [0:0] _i_blk_i2__inpad;
    wire [0:0] _i_blk_i2__opin;
    wire [0:0] _i_blk_i2__oe;
    wire [0:0] _i_blk_i2__prog_dout;
    wire [0:0] _i_blk_i2__prog_we_o;
    wire [0:0] _i_blk_i3__inpad;
    wire [0:0] _i_blk_i3__opin;
    wire [0:0] _i_blk_i3__oe;
    wire [0:0] _i_blk_i3__prog_dout;
    wire [0:0] _i_blk_i3__prog_we_o;
    wire [0:0] _i_blk_i4__inpad;
    wire [0:0] _i_blk_i4__opin;
    wire [0:0] _i_blk_i4__oe;
    wire [0:0] _i_blk_i4__prog_dout;
    wire [0:0] _i_blk_i4__prog_we_o;
    wire [0:0] _i_blk_i5__inpad;
    wire [0:0] _i_blk_i5__opin;
    wire [0:0] _i_blk_i5__oe;
    wire [0:0] _i_blk_i5__prog_dout;
    wire [0:0] _i_blk_i5__prog_we_o;
    wire [0:0] _i_blk_i6__inpad;
    wire [0:0] _i_blk_i6__opin;
    wire [0:0] _i_blk_i6__oe;
    wire [0:0] _i_blk_i6__prog_dout;
    wire [0:0] _i_blk_i6__prog_we_o;
    wire [0:0] _i_blk_i7__inpad;
    wire [0:0] _i_blk_i7__opin;
    wire [0:0] _i_blk_i7__oe;
    wire [0:0] _i_blk_i7__prog_dout;
    wire [0:0] _i_blk_i7__prog_we_o;
    wire [0:0] _i_blk_i8__inpad;
    wire [0:0] _i_blk_i8__opin;
    wire [0:0] _i_blk_i8__oe;
    wire [0:0] _i_blk_i8__prog_dout;
    wire [0:0] _i_blk_i8__prog_we_o;
    wire [0:0] _i_blk_i9__inpad;
    wire [0:0] _i_blk_i9__opin;
    wire [0:0] _i_blk_i9__oe;
    wire [0:0] _i_blk_i9__prog_dout;
    wire [0:0] _i_blk_i9__prog_we_o;
    wire [0:0] _i_cbox_w0__bp_x0y0i0_outpad;
    wire [19:0] _i_cbox_w0__cu_u1y0n_L1;
    wire [19:0] _i_cbox_w0__cu_u1y0s_L1;
    wire [0:0] _i_cbox_w0__bp_x0y0i1_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i2_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i3_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i4_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i5_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i6_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i7_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i8_outpad;
    wire [0:0] _i_cbox_w0__bp_x0y0i9_outpad;
    wire [19:0] _i_cbox_w0__cu_u1y0n_L4;
    wire [19:0] _i_cbox_w0__cu_u1y0s_L4;
    wire [0:0] _i_cbox_w0__prog_dout;
    wire [0:0] _i_cbox_w0__prog_we_o;
    wire [0:0] _i_buf_prog_rst_l0__Q;
    wire [0:0] _i_buf_prog_done_l0__Q;
    wire [0:0] _i_buf_prog_rst_l1__Q;
    wire [0:0] _i_buf_prog_done_l1__Q;
        
    prga_iob i_blk_i0 (
        .outpad(_i_cbox_w0__bp_x0y0i0_outpad)
        ,.inpad(_i_blk_i0__inpad)
        ,.ipin(ipin_x0y0_0)
        ,.opin(_i_blk_i0__opin)
        ,.oe(_i_blk_i0__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(prog_we)
        ,.prog_din(prog_din)
        ,.prog_dout(_i_blk_i0__prog_dout)
        ,.prog_we_o(_i_blk_i0__prog_we_o)
        );
    prga_iob i_blk_i1 (
        .outpad(_i_cbox_w0__bp_x0y0i1_outpad)
        ,.inpad(_i_blk_i1__inpad)
        ,.ipin(ipin_x0y0_1)
        ,.opin(_i_blk_i1__opin)
        ,.oe(_i_blk_i1__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i0__prog_we_o)
        ,.prog_din(_i_blk_i0__prog_dout)
        ,.prog_dout(_i_blk_i1__prog_dout)
        ,.prog_we_o(_i_blk_i1__prog_we_o)
        );
    prga_iob i_blk_i2 (
        .outpad(_i_cbox_w0__bp_x0y0i2_outpad)
        ,.inpad(_i_blk_i2__inpad)
        ,.ipin(ipin_x0y0_2)
        ,.opin(_i_blk_i2__opin)
        ,.oe(_i_blk_i2__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i1__prog_we_o)
        ,.prog_din(_i_blk_i1__prog_dout)
        ,.prog_dout(_i_blk_i2__prog_dout)
        ,.prog_we_o(_i_blk_i2__prog_we_o)
        );
    prga_iob i_blk_i3 (
        .outpad(_i_cbox_w0__bp_x0y0i3_outpad)
        ,.inpad(_i_blk_i3__inpad)
        ,.ipin(ipin_x0y0_3)
        ,.opin(_i_blk_i3__opin)
        ,.oe(_i_blk_i3__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i2__prog_we_o)
        ,.prog_din(_i_blk_i2__prog_dout)
        ,.prog_dout(_i_blk_i3__prog_dout)
        ,.prog_we_o(_i_blk_i3__prog_we_o)
        );
    prga_iob i_blk_i4 (
        .outpad(_i_cbox_w0__bp_x0y0i4_outpad)
        ,.inpad(_i_blk_i4__inpad)
        ,.ipin(ipin_x0y0_4)
        ,.opin(_i_blk_i4__opin)
        ,.oe(_i_blk_i4__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i3__prog_we_o)
        ,.prog_din(_i_blk_i3__prog_dout)
        ,.prog_dout(_i_blk_i4__prog_dout)
        ,.prog_we_o(_i_blk_i4__prog_we_o)
        );
    prga_iob i_blk_i5 (
        .outpad(_i_cbox_w0__bp_x0y0i5_outpad)
        ,.inpad(_i_blk_i5__inpad)
        ,.ipin(ipin_x0y0_5)
        ,.opin(_i_blk_i5__opin)
        ,.oe(_i_blk_i5__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i4__prog_we_o)
        ,.prog_din(_i_blk_i4__prog_dout)
        ,.prog_dout(_i_blk_i5__prog_dout)
        ,.prog_we_o(_i_blk_i5__prog_we_o)
        );
    prga_iob i_blk_i6 (
        .outpad(_i_cbox_w0__bp_x0y0i6_outpad)
        ,.inpad(_i_blk_i6__inpad)
        ,.ipin(ipin_x0y0_6)
        ,.opin(_i_blk_i6__opin)
        ,.oe(_i_blk_i6__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i5__prog_we_o)
        ,.prog_din(_i_blk_i5__prog_dout)
        ,.prog_dout(_i_blk_i6__prog_dout)
        ,.prog_we_o(_i_blk_i6__prog_we_o)
        );
    prga_iob i_blk_i7 (
        .outpad(_i_cbox_w0__bp_x0y0i7_outpad)
        ,.inpad(_i_blk_i7__inpad)
        ,.ipin(ipin_x0y0_7)
        ,.opin(_i_blk_i7__opin)
        ,.oe(_i_blk_i7__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i6__prog_we_o)
        ,.prog_din(_i_blk_i6__prog_dout)
        ,.prog_dout(_i_blk_i7__prog_dout)
        ,.prog_we_o(_i_blk_i7__prog_we_o)
        );
    prga_iob i_blk_i8 (
        .outpad(_i_cbox_w0__bp_x0y0i8_outpad)
        ,.inpad(_i_blk_i8__inpad)
        ,.ipin(ipin_x0y0_8)
        ,.opin(_i_blk_i8__opin)
        ,.oe(_i_blk_i8__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i7__prog_we_o)
        ,.prog_din(_i_blk_i7__prog_dout)
        ,.prog_dout(_i_blk_i8__prog_dout)
        ,.prog_we_o(_i_blk_i8__prog_we_o)
        );
    prga_iob i_blk_i9 (
        .outpad(_i_cbox_w0__bp_x0y0i9_outpad)
        ,.inpad(_i_blk_i9__inpad)
        ,.ipin(ipin_x0y0_9)
        ,.opin(_i_blk_i9__opin)
        ,.oe(_i_blk_i9__oe)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i8__prog_we_o)
        ,.prog_din(_i_blk_i8__prog_dout)
        ,.prog_dout(_i_blk_i9__prog_dout)
        ,.prog_we_o(_i_blk_i9__prog_we_o)
        );
    cbox_prga_t_iob_w0 i_cbox_w0 (
        .bp_x0y0i0_outpad(_i_cbox_w0__bp_x0y0i0_outpad)
        ,.bi_u1y0n_L1(bi_u1y0n_L1)
        ,.bi_u1y0s_L1(bi_u1y0s_L1)
        ,.bp_x0y0i0_inpad(_i_blk_i0__inpad)
        ,.cu_u1y0n_L1(_i_cbox_w0__cu_u1y0n_L1)
        ,.cu_u1y0s_L1(_i_cbox_w0__cu_u1y0s_L1)
        ,.bp_x0y0i1_outpad(_i_cbox_w0__bp_x0y0i1_outpad)
        ,.bp_x0y0i1_inpad(_i_blk_i1__inpad)
        ,.bp_x0y0i2_outpad(_i_cbox_w0__bp_x0y0i2_outpad)
        ,.bp_x0y0i2_inpad(_i_blk_i2__inpad)
        ,.bp_x0y0i3_outpad(_i_cbox_w0__bp_x0y0i3_outpad)
        ,.bp_x0y0i3_inpad(_i_blk_i3__inpad)
        ,.bp_x0y0i4_outpad(_i_cbox_w0__bp_x0y0i4_outpad)
        ,.bp_x0y0i4_inpad(_i_blk_i4__inpad)
        ,.bp_x0y0i5_outpad(_i_cbox_w0__bp_x0y0i5_outpad)
        ,.bp_x0y0i5_inpad(_i_blk_i5__inpad)
        ,.bp_x0y0i6_outpad(_i_cbox_w0__bp_x0y0i6_outpad)
        ,.bp_x0y0i6_inpad(_i_blk_i6__inpad)
        ,.bp_x0y0i7_outpad(_i_cbox_w0__bp_x0y0i7_outpad)
        ,.bp_x0y0i7_inpad(_i_blk_i7__inpad)
        ,.bp_x0y0i8_outpad(_i_cbox_w0__bp_x0y0i8_outpad)
        ,.bp_x0y0i8_inpad(_i_blk_i8__inpad)
        ,.bp_x0y0i9_outpad(_i_cbox_w0__bp_x0y0i9_outpad)
        ,.bp_x0y0i9_inpad(_i_blk_i9__inpad)
        ,.bi_u1y0n_L4(bi_u1y0n_L4)
        ,.bi_u1y0s_L4(bi_u1y0s_L4)
        ,.bi_u1v2n_L4(bi_u1v2n_L4)
        ,.bi_u1y2s_L4(bi_u1y2s_L4)
        ,.cu_u1y0n_L4(_i_cbox_w0__cu_u1y0n_L4)
        ,.cu_u1y0s_L4(_i_cbox_w0__cu_u1y0s_L4)
        ,.bi_u1v1n_L4(bi_u1v1n_L4)
        ,.bi_u1y1s_L4(bi_u1y1s_L4)
        ,.bi_u1v3n_L4(bi_u1v3n_L4)
        ,.bi_u1y3s_L4(bi_u1y3s_L4)
        ,.prog_clk(prog_clk)
        ,.prog_rst(_i_buf_prog_rst_l1__Q)
        ,.prog_done(_i_buf_prog_done_l1__Q)
        ,.prog_we(_i_blk_i9__prog_we_o)
        ,.prog_din(_i_blk_i9__prog_dout)
        ,.prog_dout(_i_cbox_w0__prog_dout)
        ,.prog_we_o(_i_cbox_w0__prog_we_o)
        );
    prga_simple_buf i_buf_prog_rst_l0 (
        .C(prog_clk)
        ,.D(_i_buf_prog_rst_l1__Q)
        ,.Q(_i_buf_prog_rst_l0__Q)
        );
    prga_simple_bufr i_buf_prog_done_l0 (
        .C(prog_clk)
        ,.R(_i_buf_prog_rst_l0__Q)
        ,.D(_i_buf_prog_done_l1__Q)
        ,.Q(_i_buf_prog_done_l0__Q)
        );
    prga_simple_buf i_buf_prog_rst_l1 (
        .C(prog_clk)
        ,.D(prog_rst)
        ,.Q(_i_buf_prog_rst_l1__Q)
        );
    prga_simple_bufr i_buf_prog_done_l1 (
        .C(prog_clk)
        ,.R(_i_buf_prog_rst_l0__Q)
        ,.D(prog_done)
        ,.Q(_i_buf_prog_done_l1__Q)
        );
        
    assign cu_u1y0n_L1 = _i_cbox_w0__cu_u1y0n_L1;
    assign cu_u1y0s_L1 = _i_cbox_w0__cu_u1y0s_L1;
    assign cu_u1y0n_L4 = _i_cbox_w0__cu_u1y0n_L4;
    assign cu_u1y0s_L4 = _i_cbox_w0__cu_u1y0s_L4;
    assign opin_x0y0_0 = _i_blk_i0__opin;
    assign oe_x0y0_0 = _i_blk_i0__oe;
    assign opin_x0y0_1 = _i_blk_i1__opin;
    assign oe_x0y0_1 = _i_blk_i1__oe;
    assign opin_x0y0_2 = _i_blk_i2__opin;
    assign oe_x0y0_2 = _i_blk_i2__oe;
    assign opin_x0y0_3 = _i_blk_i3__opin;
    assign oe_x0y0_3 = _i_blk_i3__oe;
    assign opin_x0y0_4 = _i_blk_i4__opin;
    assign oe_x0y0_4 = _i_blk_i4__oe;
    assign opin_x0y0_5 = _i_blk_i5__opin;
    assign oe_x0y0_5 = _i_blk_i5__oe;
    assign opin_x0y0_6 = _i_blk_i6__opin;
    assign oe_x0y0_6 = _i_blk_i6__oe;
    assign opin_x0y0_7 = _i_blk_i7__opin;
    assign oe_x0y0_7 = _i_blk_i7__oe;
    assign opin_x0y0_8 = _i_blk_i8__opin;
    assign oe_x0y0_8 = _i_blk_i8__oe;
    assign opin_x0y0_9 = _i_blk_i9__opin;
    assign oe_x0y0_9 = _i_blk_i9__oe;
    assign prog_dout = _i_cbox_w0__prog_dout;
    assign prog_we_o = _i_cbox_w0__prog_we_o;

endmodule
