// Copyright (c) 2024 Princeton University
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the copyright holder nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module prga_fifo #(
    parameter DEPTH_LOG2 = 1,
    parameter DATA_WIDTH = 32,
    parameter LOOKAHEAD = 0
) (
    input wire [0:0] clk,
    input wire [0:0] rst,

    output wire [0:0] full,
    input wire [0:0] wr,
    input wire [DATA_WIDTH - 1:0] din,

    output wire [0:0] empty,
    input wire [0:0] rd,
    output wire [DATA_WIDTH - 1:0] dout
    );

    reg [DEPTH_LOG2:0] wr_ptr, rd_ptr;
    wire empty_internal, rd_internal;
    wire [DATA_WIDTH - 1:0] ram_dout;

    prga_ram_1r1w #(
        .DATA_WIDTH         (DATA_WIDTH)
        ,.ADDR_WIDTH        (DEPTH_LOG2)
    ) ram (
        .clk                (clk)
        ,.rst               (rst)
        ,.re                (!empty_internal && rd_internal)
        ,.raddr             (rd_ptr[0 +: DEPTH_LOG2])
        ,.dout              (ram_dout)
        ,.waddr             (wr_ptr[0 +: DEPTH_LOG2])
        ,.din               (din)
        ,.we                (!full && wr)
        ,.bw                ({DATA_WIDTH {1'b1} })
        );

    always @(posedge clk) begin
        if (rst) begin
            wr_ptr <= 'b0;
            rd_ptr <= 'b0;
        end else begin
            if (~full && wr) begin
                wr_ptr <= wr_ptr + 1;
            end

            if (~empty_internal && rd_internal) begin
                rd_ptr <= rd_ptr + 1;
            end
        end
    end

    assign full = rd_ptr == {~wr_ptr[DEPTH_LOG2], wr_ptr[0 +: DEPTH_LOG2]};
    assign empty_internal = rd_ptr == wr_ptr;

    generate if (LOOKAHEAD) begin
        prga_fifo_lookahead_buffer #(
            .DATA_WIDTH             (DATA_WIDTH)
            ,.REVERSED              (0)
        ) buffer (
            .clk                    (clk)
            ,.rst                   (rst)
            ,.empty_i               (empty_internal)
            ,.rd_i                  (rd_internal)
            ,.dout_i                (ram_dout)
            ,.empty                 (empty)
            ,.rd                    (rd)
            ,.dout                  (dout)
            );
    end else begin
        assign rd_internal = rd;
        assign dout = ram_dout;
        assign empty = empty_internal;
    end endgenerate

endmodule